### ISSUE TITLE
Facebook share can't transfer facebook client

### ISSUE THREAD

**Issue by tianyaoxinyu** [facebook/facebook-android-sdk#577]
2019-09-11 17:36:33.377 4532-4532/come.lovemee.dating W/System.err: API_ERROR: API_ERROR
2019-09-11 17:36:33.377 4532-4532/come.lovemee.dating W/System.err:     at com.facebook.internal.NativeProtocol.getExceptionFromErrorData(NativeProtocol.java:811)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at com.facebook.share.internal.ShareInternalUtility.handleActivityResult(ShareInternalUtility.java:169)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at com.facebook.share.internal.ShareInternalUtility$3.onActivityResult(ShareInternalUtility.java:261)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:91)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at come.lovemee.dating.minframe.activity.MinDetailsActivity.onActivityResult(MinDetailsActivity.java:161)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:7690)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4928)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4975)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at android.app.ActivityThread.-wrap20(Unknown Source:0)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
2019-09-11 17:36:33.378 4532-4532/come.lovemee.dating W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:108)
2019-09-11 17:36:33.379 4532-4532/come.lovemee.dating W/System.err:     at android.os.Looper.loop(Looper.java:166)
2019-09-11 17:36:33.379 4532-4532/come.lovemee.dating W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7425)
2019-09-11 17:36:33.379 4532-4532/come.lovemee.dating W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-09-11 17:36:33.379 4532-4532/come.lovemee.dating W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
2019-09-11 17:36:33.379 4532-4532/come.lovemee.dating W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by KylinChang** [comment]
Hi @tianyaoxinyu , can you share more information like SDK version and device model?
