### ISSUE TITLE
Crash at com.facebook.internal.instrument.crashreport.CrashHandler.sendCrashReports after upgrading to 5.5.1

### ISSUE THREAD

**Issue by yuki7wang** [facebook/facebook-android-sdk#590]
Hi,
We got a crash report from few of our users.
It mainly happened on Android 8 or 9, not rooted, 
Facebook SDK v5.5.1.

Stack trace:
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at com.facebook.internal.instrument.crashreport.CrashHandler.sendCrashReports + 103(CrashHandler.java:103)
       at com.facebook.internal.instrument.crashreport.CrashHandler.enable + 73(CrashHandler.java:73)
       at com.facebook.internal.instrument.InstrumentManager$1.onCompleted + 49(InstrumentManager.java:49)
       at com.facebook.internal.FeatureManager$1.onCompleted + 39(FeatureManager.java:39)
       at com.facebook.internal.FetchedAppGateKeepersManager$2.run + 156(FetchedAppGateKeepersManager.java:156)
       at android.os.Handler.handleCallback + 790(Handler.java:790)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 164(Looper.java:164)
       at android.app.ActivityThread.main + 7000(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 441(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main + 1408(ZygoteInit.java:1408)

**Comment by shashankpsingh** [comment]
Hey same here,
I am on FB SDK version 5.5.0 

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'com.facebook.internal.l com.facebook.internal.k.a' on a null object reference
       at com.facebook.internal.FeatureManager$1.onCompleted(FeatureManager.java:39)
       at com.facebook.internal.FetchedAppGateKeepersManager$2.run(FetchedAppGateKeepersManager.java:154)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:7055)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

**Comment by KylinChang** [comment]
Hi @yuki7wang , @shashankpsingh , I have submitted a fix for that https://github.com/facebook/facebook-android-sdk/commit/59d55219edc8c852cabcf2d8cf41ed1c3ef6c7a8 and it will be shipped in the next release.

**Comment by cdaunique** [comment]
Hello,
Do you know when the version  **5.5.2** might be available on Maven Central ?
I had version 5.4.0 included in my app before which led to thousands of ANRs in Google Play Console as described in issue #574 
It seems to have been fixed in release **5.5.1** but I'm kinda afraid to bump to this version if it can cause crashes on the other hand :/

**Comment by KylinChang** [comment]
Hey @cdaunique , the issues you mentioned (ANR and this issue) are addressed in v5.5.2, you can now upgrade to v5.5.2.

**Comment by shashankpsingh** [comment]
Hey again got the issue on version 5.8.0

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'com.facebook.internal.l com.facebook.internal.k.a' on a null object reference
       at com.facebook.internal.FeatureManager$1.onCompleted(FeatureManager.java:39)
       at com.facebook.internal.FetchedAppGateKeepersManager$2.run(FetchedAppGateKeepersManager.java:154)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6626)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
