### ISSUE TITLE
com.facebook.internal.WebDialog.access$500 WebDialog.java

### ISSUE THREAD

**Issue by AmitPrajapati1902** [facebook/facebook-android-sdk#649]
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {myapppackage/com.facebook.FacebookActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f070077
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5415)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
       at de.robv.android.xp0sed.Xp0sedBridge.main(Xp0sedBridge.java:102)

I'm simply open

**Comment by carlos-mg89** [comment]
Same is happening to 2 of my users. The relevant stack trace I found is this one:

```
android.content.res.Resources.getValue (Resources.java:1266)
android.content.res.Resources.getDrawable (Resources.java:785)
android.content.res.Resources.getDrawable (Resources.java:752)
com.facebook.internal.WebDialog.createCrossImage (WebDialog.java:522)
com.facebook.internal.WebDialog.onCreate (WebDialog.java:395)
android.app.Dialog.dispatchOnCreate (Dialog.java:373)
android.app.Dialog.show (Dialog.java:274)
androidx.fragment.app.DialogFragment.onStart (DialogFragment.java:486)
androidx.fragment.app.Fragment.performStart (Fragment.java:2632)
androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:915)
androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManagerImpl.java:1238)
androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:1303)
androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java:439)
androidx.fragment.app.FragmentManagerImpl.executeOps (FragmentManagerImpl.java:2079)
androidx.fragment.app.FragmentManagerImpl.executeOpsTogether (FragmentManagerImpl.java:1869)
androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManagerImpl.java:1824)
androidx.fragment.app.FragmentManagerImpl.execPendingActions (FragmentManagerImpl.java:1727)
androidx.fragment.app.FragmentManagerImpl.dispatchStateChange (FragmentManagerImpl.java:2663)
androidx.fragment.app.FragmentManagerImpl.dispatchResume (FragmentManagerImpl.java:2625)
androidx.fragment.app.FragmentController.dispatchResume (FragmentController.java:268)
androidx.fragment.app.FragmentActivity.onResumeFragments (FragmentActivity.java:479)
androidx.fragment.app.FragmentActivity.onPostResume (FragmentActivity.java:468)
android.app.Activity.performResume (Activity.java:6088)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:2999)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3041)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2397)
android.app.ActivityThread.access$800 (ActivityThread.java:156)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1308)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5314)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:373)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:903)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:698)
```

And Firebase highlights these 2 lines:
```
com.facebook.internal.WebDialog.createCrossImage (WebDialog.java:522)
com.facebook.internal.WebDialog.onCreate (WebDialog.java:395)
```

I guess it's the same error as above, since I also have that stacktrace.

**Comment by pallavc34** [comment]
Even I am getting the same stack trace from 2 users. Not printing the stack trace due to obvious reasons

**Comment by ecauende** [comment]
Also have seen this crash at `com.facebook.internal.WebDialog.createCrossImage` as mentioned above. Version `7.1.0`.
