### ISSUE TITLE
WebLoginMethodHandler.java line 162 com.facebook.login.WebLoginMethodHandler.onComplete

### ISSUE THREAD

**Issue by mwbaek** [facebook/facebook-android-sdk#713]
- Android SDK Version: 6.0.0 ~ 9.0.0
- Installation Platform & Verison: Gradle version facebook sdk:6.1.0

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.facebook.AccessToken.f()' on a null object reference
       at com.facebook.login.WebLoginMethodHandler.onComplete(WebLoginMethodHandler.java:162)
       at com.facebook.login.WebViewLoginMethodHandler.onWebDialogComplete(WebViewLoginMethodHandler.java:106)
       at com.facebook.login.WebViewLoginMethodHandler$1.onComplete(WebViewLoginMethodHandler.java:75)
       at com.facebook.internal.WebDialog.sendSuccessToListener(WebDialog.java:488)
       at com.facebook.internal.WebDialog$DialogWebViewClient.shouldOverrideUrlLoading(WebDialog.java:605)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:16)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by Mxiim** [comment]
Can you provide more details how you get this error? A sample app for example.

**Comment by mwbaek** [comment]
Hi,

I reported from Firebase Crashlytics and Google Play Console Crashs.

Sample code is attached.

[crash.txt](https://github.com/facebook/facebook-android-sdk/files/4336859/crash.txt)

Thanks.

**Comment by 54lazycat** [comment]
I got similar issue when use SDK 8.1;But it's hard to reproduce

`com.facebook.login.WebLoginMethodHandler.onComplete (WebLoginMethodHandler.java:147)
com.facebook.login.CustomTabLoginMethodHandler.onCustomTabComplete (CustomTabLoginMethodHandler.java:182)
com.facebook.login.CustomTabLoginMethodHandler.onActivityResult (CustomTabLoginMethodHandler.java:137)
com.facebook.login.LoginClient.onActivityResult (LoginClient.java:159)
com.facebook.login.LoginFragment.onActivityResult (LoginFragment.java:180)`
