### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{xx.xx.xx/com.facebook.CustomTabMainActivity}

### ISSUE THREAD

**Issue by 10045125** [facebook/facebook-android-sdk#788]
java.lang.RuntimeException: Unable to start activity ComponentInfo{xx.xx.xx/com.facebook.CustomTabMainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://m.facebook.com/... flg=0x40000000 pkg=com.android.chrome (has extras) }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2485)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
	at android.app.ActivityThread.access$1100(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://m.facebook.com/... flg=0x40000000 pkg=com.android.chrome (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
	at android.app.Activity.startActivityForResult(Activity.java:4028)
	at android.app.Activity.startActivityForResult(Activity.java:3989)
	at android.app.Activity.startActivity(Activity.java:4312)
	at androidx.core.content.b.a(ContextCompat.java:251)
	at androidx.browser.customtabs.c.a(CustomTabsIntent.java:263)
	at com.facebook.internal.c.a(CustomTab.java:56)
	at com.facebook.CustomTabMainActivity.onCreate(CustomTabMainActivity.java:68)
	at android.app.Activity.performCreate(Activity.java:6355)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2438)
	... 9 more

**Comment by AlexeyGodyaev** [comment]
Android 9  Pixel 3 XL 
Background no
Root-статус yes

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxx.xxxx/com.facebook.CustomTabMainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method qd.j.e, parameter action
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method qd.j.e, parameter action
	at com.facebook.internal.CustomTab.<init>(CustomTab.java:61)
	at com.facebook.CustomTabMainActivity.onCreate(CustomTabMainActivity.java:82)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more
