### ISSUE TITLE
Crash happens in com.facebook.internal.InstallReferrerUtil

### ISSUE THREAD

**Issue by xiaoqian0408** [facebook/facebook-android-sdk#817]
Hi,
we just rolled out our release with facebook sdk 7.1.0, and a crash was reported

Fatal Exception: java.lang.SecurityException
Binder invocation to an incorrect interface
android.os.Parcel.createException (Parcel.java:1950)
android.os.Parcel.readException (Parcel.java:1918)
android.os.Parcel.readException (Parcel.java:1868)
com.google.android.a.a.a (a.java:6)
com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.a (IGetInstallReferrerService.java:4)
com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer (InstallReferrerClientImpl.java:9)
com.facebook.internal.InstallReferrerUtil$1.onInstallReferrerSetupFinished (InstallReferrerUtil.java:58)
com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected (InstallReferrerClientImpl.java:7)
android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1730)
android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1762)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6718)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

It appears something wrong happened inside com.facebook.internal.InstallReferrerUtil.

I'm not able to reproduce it since it's reported by firebase, and happened on a few user devices.

please take a look, thanks.

**Comment by rbarinov** [comment]
walkaround:

add ```-keep class com.google.android.** { *; }``` to proguard rules to fix it

**Comment by xiaoqian0408** [comment]
I still see it in our recent releases.

**Comment by shaileshmota** [comment]
Hey Hey! 

We using version : `8.1.0`  and notice crash reports :  

```text
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean psb.e()' on a null object reference
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2391)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at com.google.android.a.a.a(a.java:5)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.a(IGetInstallReferrerService.java:4)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:4)
       at com.facebook.internal.InstallReferrerUtil$1.onInstallReferrerSetupFinished(InstallReferrerUtil.java:35)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:5)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
```

Can we get an update if the issue fixed on latest versions or still a WIP ?
(Definitely not a stale issue)

**Comment by arindamxd** [comment]
The same crash occurred for me in `7.0.1`

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean pps.e()' on a null object reference
      at android.os.Parcel.createException(Parcel.java:1959)
      at android.os.Parcel.readException(Parcel.java:1921)
      at android.os.Parcel.readException(Parcel.java:1871)
      at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.getInstallReferrer(IGetInstallReferrerService.java:118)
      at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:187)
      at com.facebook.internal.InstallReferrerUtil$1.onInstallReferrerSetupFinished(InstallReferrerUtil.java:58)
      at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:222)
      at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1738)
      at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1770)
      at android.os.Handler.handleCallback(Handler.java:873)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:201)
      at android.app.ActivityThread.main(ActivityThread.java:6820)
      at java.lang.reflect.Method.invoke(Method.java)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
```

any solution?

**Comment by AlfonChitoSalano** [comment]
im getting this issue as well using 7.1.0 version

**Comment by hatimmts** [comment]
Me too, ![Screenshot_2021-05-21-23-36-06-360_com.google.android.apps.playconsole.jpg](https://user-images.githubusercontent.com/68388188/119195451-57230500-ba8d-11eb-9cff-08055752ed57.jpg)

**Comment by mainhc** [comment]
0
ANR_EXCEPTION: ANR Input dispatching timed out (b995032 com.moengames.svl/org.cocos2dx.javascript.AppActivity (server) is not responding. Waited 5002ms for MotionEvent(action=UP))
1
android.os.BinderProxy.transactNative(Native Method)
2
android.os.BinderProxy.transact(BinderProxy.java:646)
3
com.google.android.a.a.b(a.java:2)
4
com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c(IGetInstallReferrerService.java:3)
5
com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:5)
6
com.facebook.internal.InstallReferrerUtil$tryConnectReferrerInfo$installReferrerStateListener$1.onInstallReferrerSetupFinished(InstallReferrerUtil.java:53)
7
com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:4)
8
android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2251)
9
android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2284)
10
android.os.Handler.handleCallback(Handler.java:942)
11
android.os.Handler.dispatchMessage(Handler.java:99)
12
android.os.Looper.loopOnce(Looper.java:211)
13
android.os.Looper.loop(Looper.java:300)
14
android.app.ActivityThread.main(ActivityThread.java:8294)
15
java.lang.reflect.Method.invoke(Native Method)
16
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
17
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
