### ISSUE TITLE
 Crash - ActivityThread.java line 3437 after upgrading to 7.1.0 version

### ISSUE THREAD

**Issue by abhishek-blackbuck** [facebook/facebook-android-sdk#828]
## Environment

- Java Version: ` 1.8.0_201-b09`
- Android SDK Version: `29`
- Installation Platform & Verison: `[Gradle]` version `4.0.1`

## Goals

Track down Facebook referral installs.

## Expected Results

No ANRs.

## Actual Results

Getting lot of ANRs for the same `Didn't find class com.facebook.CustomTabActivity`

## Steps to Reproduce

Update to the latest `7.1.0` version of the library and the crashes seems to increase exponentially.

## Note

I'm using only Facebook core(Analytics) and Facebook App links dependancy. Below are the imports for my project --

`implementation "com.facebook.android:facebook-core:7.1.0"`
`implementation "com.facebook.android:facebook-applinks:7.1.0"`

## Stacktrace

There are 2 crashes which relates to the same origin --

1.
```
Caused by java.lang.ClassNotFoundException
Didn't find class "com.facebook.CustomTabActivity" on path: DexPathList[[zip file "/data/app/xx.xx.xx-tuhiCCinn4mp4XthbUCSmA==/base.apk"],nativeLibraryDirectories=[/data/app/xx.xx.xx-tuhiCCinn4mp4XthbUCSmA==/lib/arm64, /data/app/xx.xx.xx-tuhiCCinn4mp4XthbUCSmA==/base.apk!/lib/arm64-v8a, /system/lib64]]

Caused by java.lang.ClassNotFoundException: Didn't find class "com.facebook.CustomTabActivity" on path: DexPathList[[zip file "/data/app/xx.xx.xx-9gUHFzBKcn8mYl7VLR_JQA==/base.apk"],nativeLibraryDirectories=[/data/app/xx.xx.xx-9gUHFzBKcn8mYl7VLR_JQA==/lib/arm64, /data/app/xx.xx.xx-9gUHFzBKcn8mYl7VLR_JQA==/base.apk!/lib/arm64-v8a, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
       at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3437)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
````

2.

````
Caused by java.lang.ClassNotFoundException
Didn't find class "com.facebook.FacebookActivity" on path: DexPathList[[zip file "/data/app/xx.xx.xx-1/base.apk"],nativeLibraryDirectories=[/data/app/xx.xx.xx-1/lib/x86, /data/app/xx.xx.xx-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]

Caused by java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookActivity" on path: DexPathList[[zip file "/data/app/xx.xx.xx-1/base.apk"],nativeLibraryDirectories=[/data/app/xx.xx.xx-1/lib/x86, /data/app/xx.xx.xx-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1076)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

````

**Comment by abhishek-blackbuck** [comment]
If we add `implementation "com.facebook.android:facebook-common:7.1.0"`, will it resolve the issue ? As I've seen that both the class belongs to the `facebook-common` module. If so, why it's crashing when I'm using only `facebook-core` and `facebook-applinks` ?

**Comment by Nathaaaalie** [comment]
Hi @abhishek-blackbuck, is that possible you provide some sample code that helps us repro?

**Comment by abhishek-blackbuck** [comment]
@Nathaaaalie this issue got resolved after adding `implementation "com.facebook.android:facebook-common:7.1.0` dependancy in my app's `build.gradle`. Now we're not getting this crash anymore on Crashlytics.
