### ISSUE TITLE
getBidderToken PatternSyntaxException

### ISSUE THREAD

**Issue by gerc99** [facebook/facebook-android-sdk#829]
```
java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 6:
\[(?<option>[^-\]]+)(?:-(?<country>\d+)-(?<state>\d+))?]
      ^
    at java.util.regex.Pattern.compileImpl(Pattern.java)
    at java.util.regex.Pattern.compile(Pattern.java:411)
    at java.util.regex.Pattern.<init>(Pattern.java:394)
    at java.util.regex.Pattern.compile(Pattern.java:381)
    at com.facebook.ads.redexgen.X.8O.<clinit>
    at com.facebook.ads.redexgen.X.XF.A00
    at com.facebook.ads.redexgen.X.XF.<init>
    at com.facebook.ads.redexgen.X.XC.A01
    at com.facebook.ads.redexgen.X.Xb.A01
    at com.facebook.ads.redexgen.X.Xb.A0B
    at com.facebook.ads.redexgen.X.5p.getBidderToken
    at com.facebook.ads.BidderTokenProvider.getBidderToken(BidderTokenProvider.java:4)
```

**Comment by Faboor** [comment]
[Fixed in 5.10.1](https://developers.facebook.com/docs/audience-network/changelog-android#5_10_1), please update to a newer version.
