### ISSUE TITLE
java.lang.OutOfMemoryError: Could not allocate JNI Env

### ISSUE THREAD

**Issue by kunalkhedkar** [facebook/facebook-android-sdk#840]
Getting Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
Utility.java
com.facebook.internal.Utility.JsonStrToMap

I am using below dependencies in my android project

    implementation 'com.facebook.android:facebook-core:5.13.0'
    implementation 'com.facebook.android:facebook-common:5.13.0'
    implementation 'com.facebook.android:facebook-applinks:5.13.0'

Observed 5-6 crashes on firebase crashlytics, stack-trace as follow

Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1337)
       at com.android.okhttp.ConnectionPool.addConnection(ConnectionPool.java:222)
       at com.android.okhttp.ConnectionPool.recycle(ConnectionPool.java:212)
       at com.android.okhttp.OkHttpClient$1.recycle(OkHttpClient.java:114)
       at com.android.okhttp.internal.http.HttpConnection$AbstractSource.endOfInput(HttpConnection.java:425)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:474)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:60)
       at com.android.okhttp.okio.RealBufferedSource.request(RealBufferedSource.java:81)
       at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:74)
       at com.android.okhttp.okio.GzipSource.consumeHeader(GzipSource.java:114)
       at com.android.okhttp.okio.GzipSource.read(GzipSource.java:73)
       at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:374)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
       at java.io.InputStreamReader.read(InputStreamReader.java:233)
       at java.io.Reader.read(Reader.java:141)
       at com.facebook.internal.Utility.JsonStrToMap(Utility.java)
       at com.facebook.GraphResponse.constructErrorResponses(GraphResponse.java)
       at com.facebook.GraphResponse.constructErrorResponses(GraphResponse.java)
       at com.facebook.GraphRequest.appendParametersToBaseUrl(GraphRequest.java)
       at com.facebook.GraphRequest.appendParametersToBaseUrl(GraphRequest.java)
       at com.facebook.GraphRequest.appendParametersToBaseUrl(GraphRequest.java)
       at com.facebook.GraphRequest.appendParametersToBaseUrl(GraphRequest.java)
       at com.facebook.GraphRequest.appendParametersToBaseUrl(GraphRequest.java)
       at com.facebook.GraphRequest.appendParametersToBaseUrl(GraphRequest.java)
       at com.facebook.internal.FetchedAppGateKeepersManager.access$400(FetchedAppGateKeepersManager.java)
       at com.facebook.internal.FetchedAppGateKeepersManager.access$000(FetchedAppGateKeepersManager.java)
       at com.facebook.internal.FetchedAppGateKeepersManager$1.run(FetchedAppGateKeepersManager.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by ajay011** [comment]
Got the same issue. Any update on this?
