### ISSUE TITLE
ANR cased by send net request on UI thread

### ISSUE THREAD

**Issue by luuillu** [facebook/facebook-android-sdk#881]
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x733a5360 self=0x760c010800
  | sysTid=25013 nice=0 cgrp=default sched=0/0 handle=0x7692ed40d0
  | state=S schedstat=( 20130422821 5850139655 37136 ) utm=1659 stm=354 core=2 HZ=100
  | stack=0x7fd449e000-0x7fd44a0000 stackSize=8192KB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/25013/stack)
  native: #00 pc 00000000000bad14  /apex/com.android.runtime/lib64/bionic/libc.so (__connect+4)
  native: #01 pc 0000000000002484  /system/lib64/libnetd_client.so ((anonymous namespace)::netdClientConnect(int, sockaddr const*, unsigned int)+252)
  native: #02 pc 000000000002d898  /apex/com.android.runtime/lib64/libjavacore.so (Linux_connect(_JNIEnv*, _jobject*, _jobject*, _jobject*, int)+144)
  at libcore.io.Linux.connect(Native method)
  at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
  at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:136)
  at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
  at libcore.io.IoBridge.connectErrno(IoBridge.java:157)
  at libcore.io.IoBridge.connect(IoBridge.java:135)
  at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
  - locked <0x0b91138d> (a java.net.SocksSocketImpl)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
  at java.net.Socket.connect(Socket.java:621)
  at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
  at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
  at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
  at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
  at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
  at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
  at dm1.I(com.google.firebase:firebase-perf@@18.0.1:5)
  at em1.getResponseCode(com.google.firebase:firebase-perf@@18.0.1:1)
  at com.facebook.GraphResponse.fromHttpConnection(GraphResponse.java:2)
  at com.facebook.GraphRequest.executeConnectionAndWait(GraphRequest.java:2)
  at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:6)
  at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:3)
  at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:2)
  at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:2)
  at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:1)
  at com.facebook.internal.FetchedAppSettingsManager.getAppSettingsQueryResponse(FetchedAppSettingsManager.java:7)
  at com.facebook.internal.FetchedAppSettingsManager.queryAppSettings(FetchedAppSettingsManager.java:3)
  at com.facebook.appevents.restrictivedatafilter.RestrictiveDataManager.initialize(RestrictiveDataManager.java:2)
  at com.facebook.appevents.restrictivedatafilter.RestrictiveDataManager.enable(RestrictiveDataManager.java:2)
  at com.facebook.appevents.AppEventsManager$2.onCompleted(AppEventsManager.java:1)
  at com.facebook.internal.FeatureManager$1.onCompleted(FeatureManager.java:1)
  at com.facebook.internal.FetchedAppGateKeepersManager$2.run(FetchedAppGateKeepersManager.java:1)
  at android.os.Handler.handleCallback(Handler.java:900)
  at android.os.Handler.dispatchMessage(Handler.java:103)
  at android.os.Looper.loop(Looper.java:219)
  at android.app.ActivityThread.main(ActivityThread.java:8375)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by 1wayticket** [comment]
We have met too

**Comment by 1wayticket** [comment]
We have met the same problem. So sad about the sdk.

**Comment by SebaDudzic** [comment]
We are developing an app with Unity and we also have an alarming increase in ANRs since mid-December. My investigation led to the same stack trace. 
I'm testing this on Samsung Galaxy S8 and it's happening 100% of the time (maybe because of developer mode). I minimize the app in a specific moment after starting it. In Google Play Console we see mostly older devices, but not only Huawei. 

Is anyone from Facebook active on GitHub issues? I see tons of threads without any response from developers. 
Our app is now marked as "Bad behaviour" because of the ANRs rate. We need to fix it ASAP.

**Comment by luuillu** [comment]
We avoid this anr by following step.

1. define this class.
```
public class BugFixUtils {
  final static String DefaultSetting =
      "{\"supports_implicit_sdk_logging\":true,\"gdpv4_nux_enabled\":false,\"android_sdk_error_categories\":[{\"name\":\"login_recoverable\",\"items\":[{\"code\":102},{\"code\":190}],\"recovery_message\":\"xxx\"}],\"app_events_session_timeout\":60,\"app_events_feature_bitmask\":65591,\"seamless_login\":1,\"smart_login_bookmark_icon_url\":\"https:\\/\\/static.xx.fbcdn.net\\/rsrc.php\\/v3\\/ys\\/r\\/C6ZutYDSaaV.png\",\"smart_login_menu_icon_url\":\"https:\\/\\/static.xx.fbcdn.net\\/rsrc.php\\/v3\\/ys\\/r\\/0iarpnwdmEx.png\",\"restrictive_data_filter_params\":\"{}\",\"aam_rules\":\"{}\",\"suggested_events_setting\":\"{\\\"production_events\\\":[],\\\"eligible_for_prediction_events\\\":[\\\"fb_mobile_add_to_cart\\\"]}\",\"id\":\"1654359314867706\"}";

  public static void fixFaceBookAnr(Context context) {
    try {
      Method method = Class.forName("com.facebook.internal.FetchedAppSettingsManager")
                           .getDeclaredMethod("parseAppSettingsFromJSON", String.class,
                                              JSONObject.class);
      method.setAccessible(true);

      JSONObject settingsJSON = new JSONObject(DefaultSetting);
      String applicationId = getFaceBookApplicationId(context);
      if (settingsJSON != null && !TextUtils.isEmpty(applicationId)) {
        method.invoke(null, applicationId, settingsJSON);
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private static String getFaceBookApplicationId(Context context) {
    ApplicationInfo ai;
    try {
      ai = context.getPackageManager()
                  .getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
    } catch (PackageManager.NameNotFoundException e) {
      return null;
    }

    if (ai == null || ai.metaData == null) {
      return null;
    }

    Object appId = ai.metaData.get(APPLICATION_ID_PROPERTY);
    if (appId instanceof String) {
      String appIdString = (String) appId;
      if (appIdString.toLowerCase(Locale.ROOT).startsWith("fb")) {
        return appIdString.substring(2);
      } else {
        return appIdString;
      }
    } else {
      return null;
    }
  }
}
 ```
2 . add proguard rule
```
-keep class  com.facebook.internal.FetchedAppSettingsManager { *; }
```

3.  Add this method on your Application class
```
  protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    BugFixUtils.fixFaceBookAnr(this);
  }
```

**Comment by iamen12345** [comment]
el meticheerrrr

**Comment by Skullper** [comment]
Still encountering it in 2022 with SDK version 12.1.0.
Any updates on this?
